[package]
name = "soccer"
version = "0.1.0"
authors = ["Adam Biltcliffe <adam.biltcliffe@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.8"
hecs = "0.6.0"
